#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
static double median;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
double * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  
  int i = 0, j = 0, tmp = 0;
  int arrayLen = input->input_data.input_data_len;

  median = 0;

  /* iterate until end of number of times (array length) */
  for(i = 0; i < arrayLen; i++) {
    for (j = 0; j < arrayLen-1; j++) {
      if (dp[j] > dp[j+1]) {
        tmp = dp[j];
        dp[j] = dp[j+1];
        dp[j+1] = tmp;
      }
    }
  }

  if ((arrayLen % 2) == 0) {
    median = (dp[(arrayLen-1)/2] + dp[arrayLen/2])/2.0;
  } 
  else {
    median = dp[arrayLen/2];
  }

  return( &median );
}

double * ascending_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  
  int i = 0, j = 0, tmp = 0;
  int arrayLen = input->input_data.input_data_len;

  median = 0;

  /* iterate until end of number of times (array length) */
  for(i = 0; i < arrayLen; i++) {
    for (j = 0; j < arrayLen-1; j++) {
      if (dp[j] > dp[j+1]) {
        tmp = dp[j];
        dp[j] = dp[j+1];
        dp[j+1] = tmp;
      }
    }
  }

  
}

double * descending_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  
  int i = 0, j = 0, tmp = 0;
  int arrayLen = input->input_data.input_data_len;

  median = 0;

  /* iterate until end of number of times (array length) */
  for(i = 0; i < arrayLen; i++) {
    for (j = 0; j < arrayLen-1; j++) {
      if (dp[j] > dp[j+1]) {
        tmp = dp[j];
        dp[j] = dp[j+1];
        dp[j+1] = tmp;
      }
    }
  }

  
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
